language: python
python:
    - "2.7"
install:
    - "pip install -r requirements-tests.txt"
script:
    - "flake8 setup.py py_look_for_timeouts tests"
    - "nosetests -s -v --with-cover --cover-package=py_look_for_timeouts tests"
